app/src/Entity/Employee.php
<?php
  
  namespace App\Entity;

  use Doctrine\Common\Collections\ArrayCollection;
  use Doctrine\Common\Collections\Collection;
  use Doctrine\ORM\Mapping as ORM;
  use Symfony\Component\Validator\Constraints as Assert;
  use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
  
  /**
   * Employee
   *
   * @ORM\Table(name="employee")
   * @ORM\Entity
   * @UniqueEntity(fields={"name", "surname"},
   *     message="This combination of NAME and SURNAME already exists.",
   *     errorPath="name"
   * )
   */
  class Employee {
    
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
    
    /**
     * @var string
     * @Assert\NotBlank()
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;
    
    /**
     * @var string
     * @Assert\NotBlank()
     * @ORM\Column(name="surname", type="string", length=255)
     */
    private $surname;
    
    /**
     * @var int|null
     * @Assert\AtLeastOneOf({
     *     @Assert\Blank(),
     *     @Assert\Length(8)
     * })
     * @ORM\Column(name="identity_card", type="integer", nullable=true)
     */
    private $identityCard;
    
    public function getId(): ?int {
      return $this->id;
    }
    
    public function getName(): ?string {
      return $this->name;
    }
    
    public function setName(?string $name): self {
      $this->name = $name;
      
      return $this;
    }
    
    public function getSurname(): ?string {
      return $this->surname;
    }
    
    public function setSurname(?string $surname): self {
      $this->surname = $surname;
      
      return $this;
    }
    
    public function getIdentityCard(): ?int {
      return $this->identityCard;
    }
    
    public function setIdentityCard(?int $identityCard): self {
      $this->identityCard = $identityCard;
      
      return $this;
    }
    
    public function __toString() {
      return $this->surname . ', ' . $this->name . ' - ' . $this->identityCard;
    }
  
    public function getFullname(): ?string {
      return $this->surname . ', ' . $this->name;
    }
    
  }

app/src/Form/Travel/EmployeesType.php
<?php
  
  namespace App\Form\EmployeesType;
  
  use App\Entity\Employee;
  use App\Entity\Travel;
  use App\Entity\TripDestination;
  use Doctrine\ORM\EntityManagerInterface;
  use Symfony\Bridge\Doctrine\Form\Type\EntityType;
  use Symfony\Component\Form\AbstractType;
  use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
  use Symfony\Component\Form\Extension\Core\Type\CollectionType;
  use Symfony\Component\Form\Extension\Core\Type\DateType;
  use Symfony\Component\Form\Extension\Core\Type\EmailType;
  use Symfony\Component\Form\Extension\Core\Type\IntegerType;
  use Symfony\Component\Form\Extension\Core\Type\SubmitType;
  use Symfony\Component\Form\FormBuilderInterface;
  use Symfony\Component\OptionsResolver\OptionsResolver;
  
  class EmployeesType extends AbstractType {
  

    public function buildForm(
      FormBuilderInterface $builder,
      array $options
    ): void {
      $builder
              ->add('employees', EntityType::class, [
                'class' => Employee::class,
                'multiple' => TRUE,
                'required' => TRUE,
                'attr' => [
                  'placeholder' => '- Required -',
                ],
                'label' => FALSE
              ]);
    }
  
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
      $resolver->setDefaults(array(
        'data_class' => Travel::class
      ));
    }
  }

app/src/Form/Travel/ResolutionType.php
<?php
  
  namespace App\Form\Travel;
  
  use App\Entity\Resolution;
  use Symfony\Bridge\Doctrine\Form\Type\EntityType;
  use Symfony\Component\Form\AbstractType;
  use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
  use Symfony\Component\Form\Extension\Core\Type\CollectionType;
  use Symfony\Component\Form\Extension\Core\Type\DateType;
  use Symfony\Component\Form\Extension\Core\Type\EmailType;
  use Symfony\Component\Form\Extension\Core\Type\FileType;
  use Symfony\Component\Form\Extension\Core\Type\IntegerType;
  use Symfony\Component\Form\Extension\Core\Type\SubmitType;
  use Symfony\Component\Form\Extension\Core\Type\TextType;
  use Symfony\Component\Form\FormBuilderInterface;
  use Symfony\Component\OptionsResolver\OptionsResolver;
  use Symfony\Component\Validator\Constraints\File;

  class ResolutionType extends AbstractType {
  

    public function buildForm(
      FormBuilderInterface $builder,
      array $options
    ): void {
      $builder
        ->add('name', TextType::class, [
          'required' => FALSE,
          'attr' => [
            'placeholder' => '- Optional -',
          ],
          'label' => 'Name',
        ])
        ->add('file',CollectionType::class,[
          'entry_type' => FileType::class,
          'entry_options' =>
            [
              'data_class' => NULL,
              'label'=> FALSE,
              'attr' => ['class' => 'col-3'],
              'mapped' => FALSE,
              'required' => FALSE,
              'constraints' => [
                new File([
                  'maxSize' => '5024k',
                  'mimeTypes' => [
                    'application/pdf',
                    'application/x-pdf',
                  ],
                  'mimeTypesMessage' => 'Please upload a valid PDF document',
                ])
              ],
            ],
          'allow_add' => TRUE,
          'prototype' => TRUE,
          'by_reference' => FALSE,
          'required' => FALSE,
          'label'=>  FALSE
        ]);
    }
  
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
      $resolver->setDefaults(array(
        'data_class' => Resolution::class
      ));
    }
  }

app/src/Form/Travel/TravelType.php
<?php
	
	namespace App\Form\Travel;
	
	use App\Entity\Travel;
	use App\Entity\TripDestination;
	use App\Repository\TripDestinationRepository;
	use Symfony\Bridge\Doctrine\Form\Type\EntityType;
	use Symfony\Component\Form\AbstractType;
	use Symfony\Component\Form\Extension\Core\Type\CollectionType;
	use Symfony\Component\Form\Extension\Core\Type\DateType;
	use Symfony\Component\Form\Extension\Core\Type\IntegerType;
	use Symfony\Component\Form\Extension\Core\Type\SubmitType;
	use Symfony\Component\Form\FormBuilderInterface;
	use Symfony\Component\OptionsResolver\OptionsResolver;
	
	class TravelType extends AbstractType
	{
		/**
		 * @var TripDestinationRepository
		 */
		private TripDestinationRepository $tripDestinationRepository;
		
		public function __construct(TripDestinationRepository $tripDestinationRepository)
		{
			$this->tripDestinationRepository = $tripDestinationRepository;
		}
		
		public function buildForm(
			FormBuilderInterface $builder,
			array $options
		): void {
			$builder
				->add('travellersNames', CollectionType::class, [
					'entry_type' => TravellersNameType::class,
					'entry_options' => ['label' => false],
					'allow_add' => true,
					'allow_delete' => true,
					'prototype' => true,
					'by_reference' => false,
					'label' => false
				
				])
				->add('tripDestinations', EntityType::class, [
					'class' => TripDestination::class,
					'multiple' => true,
					'required' => true,
					'empty_data' => '',// fix rendering errors replace the default value ( [] )
					'choices' => $this->tripDestinationRepository->findByLocationCostsNotNull(),
					'choice_attr' => function (TripDestination $tripDestination, $key, $index) {
						return ['data-cost' => $tripDestination->getLocationCosts()->getCost()];
					},
					'label' => 'Destinations',
					'label_attr' => ['class' => 'w-100'],
					'attr' => [
						'required' => 'required'
					],
					'placeholder' => 'Required'
				])
				->add('departureDate', DateType::class, [
					'widget' => 'single_text',
					'required' => true,
					'label' => 'Departure Date',
					'empty_data' => '',
          'attr' => ['max' => date('Y-m-d')],
				])
				->add('arrivalDate', DateType::class, [
					'widget' => 'single_text',
					'required' => true,
					'label' => 'Arrival Date',
          'attr' => ['max' => date('Y-m-d')],
				])
				->add('resolution', ResolutionType::class, [
					'label' => false
				])
				->add('expenses', IntegerType::class, [
					'required' => true,
					'attr' => [
						'placeholder' => '- Required -',
					],
					'label' => 'Expenses',
				])
				->add('save', SubmitType::class, [
					'attr' => ['class' => 'btn btn-success col-12 col-sm-4 col-md-2 col-lg-2'],
					'label' => 'Save',
				]);
		}
		
		public function configureOptions(OptionsResolver $resolver): void
		{
			$resolver->setDefaults([
				'data_class' => Travel::class,
				'attr' => ['id' => 'form', 'novalidate' => 'novalidate']
			]);
		}
	}

app/src/Form/Travel/TravellersNameType.php
<?php
  
  namespace App\Form\Travel;
  
  use App\Entity\Employee;
  use App\Entity\TravellersName;
  use Symfony\Bridge\Doctrine\Form\Type\EntityType;
  use Symfony\Component\Form\AbstractType;
  use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
  use Symfony\Component\Form\Extension\Core\Type\CollectionType;
  use Symfony\Component\Form\Extension\Core\Type\DateType;
  use Symfony\Component\Form\Extension\Core\Type\EmailType;
  use Symfony\Component\Form\Extension\Core\Type\IntegerType;
  use Symfony\Component\Form\Extension\Core\Type\SubmitType;
  use Symfony\Component\Form\FormBuilderInterface;
  use Symfony\Component\OptionsResolver\OptionsResolver;
  
  class TravellersNameType extends AbstractType {
  

    public function buildForm(
      FormBuilderInterface $builder,
      array $options
    ): void {
      $builder
              ->add('employee', EntityType::class, [
                'class' => Employee::class,
                'multiple' => FALSE,
                'required' => TRUE,
                'attr' => [
                  'class' => 'row col-12',
                  'autofocus' => 'autofocus',
                ],
                'placeholder' => '- Required -',
                'label' => 'Employee',
                'label_attr' => ['class' => 'row col-12'],
              ])
              ->add('replacement', EntityType::class, [
                'class' => Employee::class,
                'multiple' => FALSE,
                'required' => FALSE,
                'attr' => [
                  'placeholder' => '- Optional -',
                  'class' => 'row col-12'
                ],
                'label' => 'Replacement',
                'label_attr' => ['class' => 'row col-12'],
              ]);
    }
  
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
      $resolver->setDefaults(array(
        'data_class' => TravellersName::class
      ));
    }
  }

app/src/Controller/TravelController.php
<?php
	
	namespace App\Controller;
	
	use App\ConstantVariables\FormConstants;
	use App\ConstantVariables\MessageConstants;
	use App\ConstantVariables\TwigFileNameConstants;
	use App\Entity\Travel;
	use App\Form\Travel\TravelType;
	use App\Repository\Doctrine\Travel\Filter;
	use App\Repository\TravelRepository;
	use App\Service\FileManager;
	use App\Service\Resolution\ResolutionFileManager;
	use Doctrine\Common\Collections\ArrayCollection;
	use Symfony\Component\HttpFoundation\JsonResponse;
	use Symfony\Component\HttpFoundation\Request;
	use Symfony\Component\HttpFoundation\Response;
	use Symfony\Component\Routing\Annotation\Route;
	use Symfony\Component\String\Slugger\SluggerInterface;
	
	/**
	 * @Route("/travel")
	 */
	class TravelController extends WebController
	{
		const TEMPLATES_FOLDER = 'backoffice/travel/';
		const INDEX_PATH = 'travel_index';
		const NEW_PATH = 'travel_new';
		const EDIT_PATH = 'travel_edit';
		const DELETE_PATH = 'travel_delete';
		const DELETE_FILE_PATH = 'travel_delete_resolution_file';
		private TravelRepository $repository;
		private SluggerInterface $slugger;
		private ResolutionFileManager $fileManager;
		
		public function __construct(
			TravelRepository $repository,
			SluggerInterface $slugger,
			ResolutionFileManager $fileManager
		) {
			$this->repository = $repository;
			$this->slugger = $slugger;
			$this->fileManager = $fileManager;
		}
		
		/**
		 * @Route("/list", name="travel_index", methods={"GET", "POST"})
		 */
		public function index(Request $request): Response
		{
			$filter = new Filter\Filter();
			$form = $this->createForm(Filter\Form::class, $filter);
			$form->handleRequest($request);
			if ($form->isSubmitted() && !$form->isValid()) {
				return $this->redirectWithErrorMessage(
					self::INDEX_PATH,
					MessageConstants::UNEXPECTED_ERROR_HAS_OCCURRED
				);
			}
			
			$pagination = $this->repository->all(
				$filter,
				$request->query->getInt('page', 1),
				$request->query->getInt('size', 10),
				$request->query->get('sort', 't.id'),
				$request->query->get('direction', 'desc')
			);
			
			return $this->render(self::TEMPLATES_FOLDER . TwigFileNameConstants::INDEX,
				[
					'pagination' => $pagination,
					'page_title' => 'Travel',
					'index_path' => self::INDEX_PATH,
					'new_path' => self::NEW_PATH,
					'edit_path' => self::EDIT_PATH,
					'delete_path' => self::DELETE_PATH,
					'form_filter' => $form->createView(),
				]);
		}
		
		/**
		 * @Route("/new", name="travel_new", methods={"GET", "POST"})
		 */
		public function new(Request $request, FileManager $fileUploader): Response
		{
			$travel = new Travel();
			$form = $this->createForm(TravelType::class, $travel);
			$form->handleRequest($request);
			
			if ($form->isSubmitted() && $form->isValid()) {
				$fileNames = $this->fileManager->uploadFiles(
					$travel->getResolution(),
					$request);
				
				$travel->getResolution()->addFile($fileNames);
				
				$this->repository->save($travel);
				
				return $this->redirectWithSuccessMessage(
					self::INDEX_PATH,
					MessageConstants::SUCCESS_MESSAGE_TO_CREATE
				);
			}
			
			return $this->renderForm(self::TEMPLATES_FOLDER . TwigFileNameConstants::NEW,
				[
					'travel' => $travel,
					'form' => $form,
					'action_to_do' => FormConstants::CREATE_ACTION_TEXT,
					'page_title' => FormConstants::CREATE_ACTION_TEXT . ' Travel',
					'index_path' => self::INDEX_PATH,
				]);
		}
		
		/**
		 * @Route("/{travel}/edit", name="travel_edit", methods={"GET", "POST"})
		 */
		public function edit(Request $request, Travel $travel): Response
		{
			$form = $this->createForm(TravelType::class, $travel);
			
			$form->handleRequest($request);
			
			if ($form->isSubmitted() && $form->isValid()) {
				
				// Create an ArrayCollection of the current Tag objects in the database
				$previuosTravellersNames = $this->repository
						->findById($travel->getId())
						->getTravellersNames();
				
				// Remove the relationship between the traveller name and the travel
				foreach ($previuosTravellersNames as $travellerName) {
					$this->repository->removeOldReferenceToTravellersNames($travellerName);
				}

				$resolution = $travel->getResolution();
				
				$fileNames = $this->fileManager->uploadFiles($travel->getResolution(),$request);
				
				$resolution->addFile($fileNames);
				
				$this->repository->removeOldReferenceToResolution($resolution);
				
				$travel->setResolution($resolution);
				
				$this->repository->save($travel);
				
				return $this->redirectWithSuccessMessage(
					self::INDEX_PATH,
					MessageConstants::SUCCESS_MESSAGE_TO_UPDATE
				);
			}
			
			return $this->renderForm(self::TEMPLATES_FOLDER . TwigFileNameConstants::EDIT,
				[
					'travel' => $travel,
					'form' => $form,
					'action_to_do' => FormConstants::UPDATE_ACTION_TEXT,
					'page_title' => FormConstants::UPDATE_ACTION_TEXT . ' Travel',
					'index_path' => self::INDEX_PATH,
					'delete_file_path' => self::DELETE_FILE_PATH
				]);
		}
		
		/**
		 * @Route("/list/{travel}", name="travel_delete", methods={"POST"})
		 */
		public function delete(Request $request, Travel $travel): Response
		{
			if (!$this->isCsrfTokenValid('delete',
				$request->request->get('_token'))) {
				return $this->redirectWithErrorMessage(
					self::INDEX_PATH,
					MessageConstants::INVALID_TOKEN_CSFR_MESSAGE
				);
			}
			
			$this->repository->delete($travel);
			
			return $this->redirectWithSuccessMessage(
				self::INDEX_PATH,
				MessageConstants::SUCCESS_MESSAGE_TO_DELETE
			);
		}
		
		/**
		 * @Route("/{travel}/{file}/delete-resolution-file", name="travel_delete_resolution_file", methods={"POST"})
		 */
		public function deleteResolutionFile(Request $request, Travel $travel, $file): JsonResponse
		{
			if (!$this->isCsrfTokenValid('delete',
				$request->request->get('_token'))) {
				return $this->json([
						'fail_invalid_csfr_token' => MessageConstants::INVALID_TOKEN_CSFR_MESSAGE
					]
				);
			}
			
			$resolution = $travel->getResolution();
			
			$this->repository->removeOldReferenceToResolution($resolution);
			
			$resolution->removeFile($file);
			
			$this->fileManager->removeFile($file);
			
			$travel->setResolution($resolution);
			
			$this->repository->save($travel);
			
			return $this->json(['success']);
		}
	}

app/templates/backoffice/travel/_delete_form.html.twig
<form method="post" action="{{ path('travel_delete', {'id': travel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ travel.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/backoffice/travel/index.html.twig
{% extends 'backoffice/list_items_base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('assets/css/select2/select2.min.css') }}">
{% endblock %}
{% block title %}  {{ section_title }} {% endblock %}
{% block page_title %} {{ section_title }} {% endblock  page_title %}
{% block table %}
    <table id="add-row"
           class="display table table-striped table-hover dataTable"
           role="grid"
           aria-describedby="add-row_info">
        <thead>
        <tr role="row">
            <th>
                {{ 'Employees and replacements'|trans }}
            </th>
            <th>
                {{ 'Destination'|trans }}
            </th>
            <th class="{{ pagination.isSorted('t.arrivalDate')? 'sorting_' ~ pagination.getDirection:'' }} d-none d-sm-table-cell">
                {{ knp_pagination_sortable(pagination, 'Departure Date'|trans, 't.departureDate') }}
            </th>
            <th class="{{ pagination.isSorted('t.arrivalDate')? 'sorting_' ~ pagination.getDirection:'' }} d-none d-sm-table-cell">
                {{ knp_pagination_sortable(pagination, 'Arrival Date'|trans, 't.arrivalDate') }}
            </th>
            <th class=" d-none d-sm-table-cell">
                Resolution
            </th>
            <th class="{{ pagination.isSorted('t.expenses')? 'sorting_' ~ pagination.getDirection:'' }} d-none d-sm-table-cell">
                {{ knp_pagination_sortable(pagination, 'Expenses'|trans, 't.expenses') }}
            </th>


            <th class="d-none d-sm-table-cell" style="width: 132.8px;">
                {{ 'Action'|trans }}
            </th>
        </tr>
        </thead>
        <tbody>
        {% for travel in pagination %}
            <tr role="row" class="odd">
                <td class=" d-table-cell d-sm-none cursor-pointer"
                    data-toggle="modal"
                    data-target="#mobile-actions-modal"
                    data-edit_path="{{ path(edit_path, {'travel': travel.id}) }}"
                    data-form_action_attribute_to_delete="{{ path(delete_path, {'travel': travel.id}) }}"
                    data-confirmation_message_to_delete=''
                    data-modal_title='{{ travel.resolution.name }}'
                    data-confirmation_message_to_delete='{{ 'The travel with resolution "%resolution%".'|trans({'%resolution%': travel.resolution.name}) }}'
                >
                    <div class="row pt-2">
                        <div class="col-10">
                            <ul>
                                <li>{{ travel.resolution.name }}</li>
                                <li>{{ travel.expenses }}</li>
                                <li>{{ travel.departureDate|date("d/m/Y") }}</li>
                                <li>{{ travel.arrivalDate|date("d/m/Y") }}</li>
                                <ul>
                                    {% for destination in travel.tripDestinations %}
                                        <li>{{ destination.name }}</li>
                                    {% endfor %}
                                </ul>

                            </ul>
                        </div>
                        <div class="col-2"><i class="fas fa-ellipsis-v"></i></div>
                    </div>
                </td>
                <td class="d-none d-sm-table-cell">
                    <ul class="row">
                        {% for travellerNames in travel.travellersNames %}
                            <li class="col-6 mt-2 mb-2">{{ travellerNames.employee is not null? travellerNames.employee.fullname:'N/A' }}</li>
                            <li class="col-6 mt-2 mb-2">{{ travellerNames.replacement is not null? travellerNames.replacement.fullname:'N/A'  }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td class="d-none d-sm-table-cell">
                    {% for destination in travel.tripDestinations %}
                        <li>{{ destination.name }}</li>
                    {% endfor %}
                </td>
                <td class="d-none d-sm-table-cell">{{ travel.departureDate|date("d/m/Y") }}</td>
                <td class="d-none d-sm-table-cell">{{ travel.arrivalDate|date("d/m/Y") }}</td>
                <td class="d-none d-sm-table-cell">{{ travel.resolution.name }}</td>
                <td class="d-none d-sm-table-cell">{{ travel.expenses }}</td>
                <td class="d-none d-sm-table-cell">
                    <div class="d-block d-sm-none">
                        <button type="button" class="btn btn-link text-dark">
                            <i class="fas fa-ellipsis-v"></i>
                        </button>
                    </div>

                    <div class="d-none d-sm-block">
                    <span class="form-button-dots">
                        <i class="fas fa-ellipsis-v"></i>
                    </span>
                        <span class="form-button-action">
                        <a href="{{ path(edit_path, {'travel': travel.id}) }}"
                           class="editItemLink btn btn-link btn-primary btn-lg">
                            <i class="fa fa-edit"></i>
                        </a>
                        <button type="button"
                                class="btn btn-link btn-danger delete"
                                data-toggle="modal"
                                data-target="#delete-confirmation-modal"
                                data-form_action_attribute_to_delete="{{ path(delete_path, {'travel': travel.id}) }}"
                                data-confirmation_message_to_delete='{{ 'The travel with resolution "%resolution%".'|trans({'%resolution%': travel.resolution.name}) }}'>
                            <i class="fa fa-times"></i>
                        </button>

                    </span>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td class="text-center" colspan="7">
                    <i class="fas fa-exclamation-circle text-info"></i> &nbsp;{{ 'No results were found.'|trans }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block form_filter_fields %}
    <div class="col-lg-12">
{#        {{ form_row(form_filter.resolution) }}#}
        {{ form_row(form_filter.expenses) }}
        {{ form_row(form_filter.travellersNames) }}
        {{ form_row(form_filter.tripDestination) }}
        {{ form_row(form_filter.resolutionName) }}
    </div>


    <div class="col-lg-12 form-group">
        <label>{{ 'Departure Date'|trans }}</label>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group {{ form_errors(form_filter.departureDateFrom)?'has-error': '' }}">
                    <div class="small">{{ 'From'|trans }}</div>
                    {{ form_widget(form_filter.departureDateFrom) }}
                    <small class="errorLabelContainer form-text text-muted text-danger">
                        <span class="has-error">{{ form_errors(form_filter.departureDateFrom) }} </span>
                    </small>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group {{ form_errors(form_filter.departureDateTill)?'has-error': '' }}">

                    {{ form_widget(form_filter.departureDateTill) }}
                    <small class="errorLabelContainer form-text text-muted text-danger">
                        <span class="has-error">{{ form_errors(form_filter.departureDateTill) }} </span>
                    </small>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-12 form-group">
        <label>Arrival Date</label>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group {{ form_errors(form_filter.arrivalDateFrom)?'has-error': '' }}">
                    <div class="small">{{ 'From'|trans }}</div>
                    {{ form_widget(form_filter.arrivalDateFrom) }}
                    <small class="errorLabelContainer form-text text-muted text-danger">
                        <span class="has-error">{{ form_errors(form_filter.arrivalDateFrom) }} </span>
                    </small>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group {{ form_errors(form_filter.arrivalDateTill)?'has-error': '' }}">
                    <div class="small">{{ 'Till'|trans }}</div>
                    {{ form_widget(form_filter.arrivalDateTill) }}
                    <small class="errorLabelContainer form-text text-muted text-danger">
                        <span class="has-error">{{ form_errors(form_filter.arrivalDateTill) }} </span>
                    </small>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('assets/js/plugin/select2/select2.full.min.js') }}"></script>
    <script>
        $(document).ready(function () {

            $('#form_travellersNames').select2({
                dropdownParent: $('#filter-modal'),
                placeholder: '- ' + Translator.trans('Filter by employee') + ' -'
            });

            $('#form_tripDestination').select2({
                dropdownParent: $('#filter-modal'),
                placeholder: '- ' + Translator.trans('Filter by trip destination') + ' -'
            });
        });
    </script>
{% endblock %}

app/templates/backoffice/travel/new.html.twig
{% extends 'backoffice/form_to_handle_item.base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('assets/css/select2/select2.min.css') }}">
{% endblock %}
{% block form_body %}

    {{ include('backoffice/travel/_form.html.twig') }}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('assets/js/plugin/select2/select2.full.min.js') }}"></script>
    <script src="{{ asset("assets/js/blog/travel/form/calculate.travel.expenses.js") }}"></script>
    <script src="{{ asset("assets/js/blog/travel/form/add.another.employee.js") }}"></script>
    <script src="{{ asset("assets/js/blog/travel/form/add.another.resolution.file.js") }}"></script>
    <script>
        $(document).ready(function () {

            $('select[name*="employee"]').select2({ placeholder: '- ' + Translator.trans('Required') + ' -'});
            $('#travel_tripDestinations').select2({ placeholder: '- ' + Translator.trans('Required') + ' -'});
            $('select[name*="replacement"]').select2({placeholder: '- ' + Translator.trans('Optional') + ' -'});
            $('.add-another-collection-widget').click();

            // set departureDate value in arrivalDate
            $('[name="travel[departureDate]"]').on('focusout',function () {
                $('[name="travel[arrivalDate]"]').val($('[name="travel[departureDate]"]').val());
            })
        });
    </script>
{% endblock  %}